import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lexend } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

import Navbar from "./components/Navbar";

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(lexend.variable)}>
        <main className="relative text-default font-lexend flex flex-col justify-between h-[100dvh] overflow-hidden">
          <section className="grow overflow-auto flex flex-col relative">
            <Navbar className="fixed top-6 left-6 w-[calc(100dvw_-_48px)]" />
            <div className="grow overflow-auto">{children}</div>
          </section>
          {/* footer */}
        </main>
      </body>
    </html>
  );
}
